ckpt_path: ???
data_path: "./data/geom"
dataset: "geom-drugs"

batch_cost: 8192
dataset_split: "test"
n_molecules: 10000
n_replicates: 3
integration_steps: 100
cat_sampling_noise_level: 1
ode_sampling_strategy: "log"

encoder_type: "unimol"  # 'unimol' or 'frad'
encoder_path: "../checkpoints/encoder_ckpts/drug_unimol_global_iter1860000.pt"
sampler: "PCSampler"  # ["PCSampler", "GtSampler", "DDIMSampler"]
rdm_ckpt: "../checkpoints/rdm_ckpts/rdm_drug_semla_unimol_global_truncated4/model/checkpoint-last.pth"  # resume from checkpoint

step_num: 250
eta: 1.0
inv_temp: 1.0
n_steps: 2  # 5
snr: 0.05

Gt_dataset: "train"  # ["train", "test", "valid"]

bucket_cost_scale: "linear"

# Allow overriding for EGNN arch since some flowmodels were not saved with a value for n_layers
n_layers: null

categorical_strategy: 'uniform-sample'


cfg_coef: -1.0
use_gate: true

rep_loss_weight: 0.1

