defaults:
  - _self_


hydra:
  sweep:
    dir: ./hydra_logs/eval_unconditional/${version}_${now:%Y-%m-%d_%H-%M-%S}/
  run:
    dir: ./hydra_logs/eval_unconditional/${version}_${now:%Y-%m-%d_%H-%M-%S}/

version: null


# General Options
use_dist: false
save_molecules: true
saved_molecules_path: null

# If you use saved molecules for analysis, please specify a dataset so that the info can be loaded. (If not use the saved ones, dataset info will be retrieved from gen args.)
dataset: ???
remove_h: ???

# Sample Parameters
n_samples: 10000
batch_size_gen: 1000
property: null

# gen Sampler Parameters
cfg: 1.0
gen_model_path: ???

# RDM Sampler Parameters
sampler: PCSampler

# GtSampler Parameters
Gt_dataset: ???
encoder_type: ???
encoder_path: ???

# DDIMSampler Parameters
rdm_ckpt: ???
step_num: ???
eta: ???

# PCSampler Parameters (includes rdm_ckpt)
inv_temp: 1.0
n_steps: 5
snr: 0.01




ddim_S: null