defaults:
  - _self_

hydra:
  sweep:
    dir: ./hydra_logs/eval_conditional/${version}_${property}_${now:%Y-%m-%d_%H-%M-%S}/
  run:
    dir: ./hydra_logs/eval_conditional/${version}_${property}_${now:%Y-%m-%d_%H-%M-%S}/

version: null


exp_name: 'debug'
classifiers_path: '../checkpoints/classifiers_ckpts/exp_class_alpha'
property: 'alpha'  # options: 'alpha', 'homo', 'lumo', 'gap', 'mu', 'Cv'
no_cuda: false  # enables CUDA training
debug_break: false  # break point or not
log_interval: 5  # break point or not
batch_size: 1000  # break point or not
iterations: 9  # break point or not
task: 'gen'  # options: 'naive', 'gen', 'qm9_second_half', 'qualitative'

gen_model_path: ../checkpoints/gen_ckpts/edm_qm9_second_half_frad_noise0.3  # Specify model path
cfg: 2.0

sampler: PCSampler  # options: 'GtSampler', 'PCSampler', 'DDIMSampler'
Gt_dataset: ???  # options: 'train', 'test', 'valid'
encoder_type: ???
encoder_path: ???

rdm_ckpt: ../checkpoints/rdm_ckpts/rdm_alpha/model/checkpoint-last.pth
step_num: ???
eta: ???

inv_temp: 1.0
n_steps: 5
snr: 0.01