

data_path: './data/geom'
dataset: 'geom-drugs'
remove_h: false
trial_run: false
device: 'cuda'

# Model args
d_model: 512
n_layers: 12
d_message: 128
d_edge: 128
n_coord_sets: 64
n_attn_heads: 32
d_message_hidden: 128
coord_norm: 'length'
size_emb: 64
max_atoms: 256
arch: 'semla'
d_rep: 512
encoder_type: 'unimol_truncated'
encoder_path: '../checkpoints/encoder_ckpts/drug_unimol6layers_noise1.5.pt'
cond_type: "adafusion"


epochs: 300
lr: 0.0003
batch_cost: 2048 # 
acc_batches: 1
gradient_clip_val: 1.0
type_loss_weight: 0.2 # 
bond_loss_weight: 1.0
charge_loss_weight: 1.0
categorical_strategy: 'uniform-sample'
lr_schedule: 'constant'
warm_up_steps: 10000
bucket_cost_scale: 'linear'
use_ema: true
self_condition: true
rep_dropout_prob: 0.1
cfg_coef: 0.0


val_check_epochs: 20
n_validation_mols: 1000
num_inference_steps: 100
cat_sampling_noise_level: 1
coord_noise_std_dev: 0.2
type_dist_temp: 1.0
time_alpha: 2.0
time_beta: 1.0
optimal_transport: 'equivariant'
resume_checkpoint: null

sampler: 'GtSampler'
rdm_ckpt: ???
step_num: 250
eta: 1.0
inv_temp: 1.0
n_steps: 10
snr: 0.05
Gt_dataset: 'train'

noise_sigma: 0.3
attn_block_num: 1
dropout: 0.0

version: adafusion_unimol6layers_truncated_dropout0.0_noise0.3_reploss0.5 # Wandb Log Version

original: false
use_gate: true

rep_loss_weight: 0.5

